# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Signalling_Agora_p2p' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Signalling_Agora_p2p
    pod 'AgoraRtcEngine_iOS', '~> 2.4.0.1'
    pod 'NIMSDK', '~> 6.5.0'

end
